Ltd 979 query status api endpoint
uktrade/lite-hmrc pull request #73
Opened 2021-07-23 16:11 UTC by dgnball

Add two new APIs routes and a sample integration test that makes use of them. The purpose of this is to allow an integration test to check that API calls made to lite-hmrc result in an email being sent to HMRC.

2021-07-25 10:19 UTC, saruniitr requested changes

2021-07-26 15:59 UTC, dgnball commented on system_tests/expected_mail_body.txt
> +3\trader\\GB123456789000\20200602\20220602\Organisation\might\248 James Key Apt. 515\Apt. 942\West Ashleyton\Farnborough\GU40 2LX
Ok, I am testing lines 1 and 2 now.

2021-07-26 16:00 UTC, dgnball commented on system_tests/hmrc_system_test.py
> +    # Remove the first and second line as it contains data that changes every time
Done

2021-07-26 16:00 UTC, dgnball commented on system_tests/hmrc_system_test.py
> +    # Remove the first and second line as it contains data that changes every time
Done

2021-07-26 16:00 UTC, dgnball commented on system_tests/hmrc_system_test.py
> +def test_send_license():
Done

2021-07-27 13:39 UTC, saruniitr requested changes
one last change otherwise looks good to me.

2021-07-27 13:39 UTC, saruniitr commented on mail/urls.py
> +    path("set-all-to-reply-sent/", views.SetAllToReplySent.as_view(), name="set_all_to_reply_sent"),
Please include them under `DEBUG` flag which is `False` in `prod` as these endpoints should not be available in `prod`

2021-07-28 06:40 UTC, dgnball commented on mail/urls.py
> +    path("set-all-to-reply-sent/", views.SetAllToReplySent.as_view(), name="set_all_to_reply_sent"),
Done

2021-07-28 06:40 UTC, dgnball commented on mail/views.py
> -    def get(self, request):
Done

2021-07-28 08:08 UTC, saruniitr requested changes

2021-07-28 08:08 UTC, saruniitr commented on mail/urls.py
> +from conf import settings
This should be `from django.conf import settings`
`settings` is actually a `dict`, it shouldn't be imported as module

2021-07-28 08:26 UTC, dgnball commented on mail/urls.py
> +from conf import settings
If I do this using django.conf, settings doesn't pick up what I put into the .env file (always set to False)

2021-07-28 14:25 UTC, dgnball commented on mail/urls.py
> +from conf import settings
Decided not to preclude test URLs with DEBUG

2021-07-28 14:31 UTC, saruniitr approved these changes

2021-07-28 14:31 UTC, merged